### ISSUE TITLE
Cookiebanner seems to not work for regional redirect

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#76] opened 2022-11-30 21:39 UTC
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/9

> **Firefox Version:** Firefox Nightly 108.0a1
> **Window Size (inner width and height):** 1300x1050
> ## Steps to Reproduce
> 1) Went to https://DHL.com as per list for foxfooding
> 2) DHL.com redirect to DHL.com/se-sv/...
> 3) Asks for permissions for cookies
>
> ## Expected Behavior
> Autorejected cookie notice.
>
> ## Actual Behavior
> Cookie notice not automatically rejected.
>
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/64e363c4-1a52-4710-b9eb-0344889b8adf.png)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/64e363c4-1a52-4710-b9eb-0344889b8adf.png)

**Comment by hokonch** [comment] 2022-12-01 18:05
Seems to be a duplicate of https://github.com/mozilla/cookie-banner-rules-list/issues/95. 
I have checked the homepages for some European countries, and it is seems the rule does not work regardless of regions, at least, with my IP geo-location.

**Comment by Softvision-ValentinBandac** [comment] 2022-12-20 10:29
I have verified that this issue is no longer reproducible using the latest V0.5.5 release on RS stage.

**Closed by Softvision-ValentinBandac** 2022-12-20 10:29 UTC
Labels: QA Verified
